# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fresh}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hsume2"]
  s.date = %q{2010-07-07}
  s.description = %q{An infant Ruby DSL for syncing local <=> remote data.}
  s.email = %q{henry.hsu@photomugs.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "fresh.gemspec",
     "lib/fresh.rb",
     "lib/fresh/core_extensions.rb",
     "lib/fresh/syncer.rb",
     "lib/fresh/wrench.rb",
     "spec/fresh/core_extensions_spec.rb",
     "spec/fresh/wrench_spec.rb",
     "spec/fresh_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hsume2/fresh}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An infant Ruby DSL for syncing local <=> remote data.}
  s.test_files = [
    "spec/fresh/core_extensions_spec.rb",
     "spec/fresh/wrench_spec.rb",
     "spec/fresh_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

